version: '3.8'

services:
    localstack:
        container_name: "${LOCALSTACK_DOCKER_NAME-local-aws}"
        image: localstack/localstack:latest
        platform: linux/x86_64
        ports:
          - 4566:4566
          - 9000:8080
        volumes:
          - ./docker/localstack:/docker-entrypoint-initaws.d
          - /var/run/docker.sock:/var/run/docker.sock
          # データのマウント
          - 'localstack-data:/tmp/localstack'
        environment:
            # s3のpresignedUrlを利用するためにはtestにしなければいけない
      # https://docs.localstack.cloud/integrations/aws-cli/#setting-up-local-region-and-credentials-to-run-localstack
          - AWS_ACCESS_KEY_ID=test
          - AWS_SECRET_ACCESS_KEY=test
          - AWS_DEFAULT_REGION=ap-northeast-1
          - DATA_DIR=/tmp/localstack/data
          - DISABLE_CORS_CHECKS=1
    
    dynamodb-local:
        image: amazon/dynamodb-local:latest
        container_name: dynamodb_local
        user: root
        command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data  # 永続化するデータのファイルパス
        volumes:
          - dynamodb-data:/data  # データの永続化
        ports:
            - 8000:8000
    dynamodb-admin:
        image: aaronshaf/dynamodb-admin:latest
        container_name: dynamodb-admin
        environment:
            - DYNAMO_ENDPOINT=dynamodb-local:8000
        ports:
            - 8001:8001
        depends_on:
            - dynamodb-local
volumes:
    localstack-data:
        driver: 'local'
    dynamodb-data:
        driver: 'local'